spring:
  # 数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simple_mall
    username: root
    password: zyy2176801587

    #文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


#阿里云oss
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5t8FjoPAcowNXfMRhVAG
    accessKeySecret: IdshgTjnUrIbcw9O4Bz6zxxsm5zmAF
    bucketName: web-tlias-yiyun


#spring 事务管理日志开关
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug


